# Generated by Django 3.1.12 on 2025-08-26 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0002_auto_20250825_0500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prize',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prize',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
