# Generated by Django 3.1.12 on 2025-08-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20250826_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prize',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='prize',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
