# Generated by Django 4.2.23 on 2025-08-26 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20250826_0416'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameResult',
        ),
        migrations.DeleteModel(
            name='Prize',
        ),
    ]
